# Generated by Django 4.0.2 on 2022-05-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Call.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numueroguia', models.CharField(max_length=50)),
                ('identificacionRemi', models.CharField(max_length=50)),
                ('nombreRemi', models.CharField(max_length=50)),
                ('direccionRemi', models.TextField()),
                ('telefonoRemi', models.CharField(max_length=50)),
                ('correoRemi', models.EmailField(max_length=254)),
                ('identificacionDesti', models.CharField(max_length=50)),
                ('nombreDesti', models.CharField(max_length=50)),
                ('direccionDesti', models.TextField()),
                ('telefonoDesti', models.CharField(max_length=50)),
                ('correoDesti', models.EmailField(max_length=254)),
                ('peso', models.CharField(max_length=50)),
                ('alto', models.CharField(max_length=50)),
                ('ancho', models.CharField(max_length=50)),
                ('largo', models.CharField(max_length=50)),
                ('contiene', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('entregado', models.BooleanField(default=False)),
                ('asignado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ciudadDesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadDesti', to='Call.municipio')),
                ('ciudadRemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadRemi', to='Call.municipio')),
                ('formapagp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Call.formapago')),
                ('tipoIdDesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoIdDesti', to='Call.tipoidentificacion')),
                ('tipoIdRemitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoIdRemitente', to='Call.tipoidentificacion')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Call.tiposervicio')),
                ('vehiculos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Envio de Guia',
                'verbose_name_plural': 'Envios de Guias',
                'db_table': 'EnvioGuia',
            },
        ),
    ]
