# Generated by Django 4.0.2 on 2022-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorIdoc', models.IntegerField(default=0)),
                ('valorAdoc', models.IntegerField(default=0)),
                ('flete', models.IntegerField(default=0)),
                ('año', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreciosPaquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorIpaq', models.IntegerField(default=0)),
                ('valorApaq', models.IntegerField(default=0)),
                ('flete', models.IntegerField(default=0)),
                ('año', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
